### ISSUE TITLE
Idea: Add config file

### ISSUE THREAD

**Issue by JuanVqz** [liondocs/cli#26]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Yes, It would be great if we have a configuration file where we can indicate the `from` and `to` directories

Ex. `$HOME/.source_commit.yml`
```js
{
  from: "/path/to/content",
  to: "/path/to/translated-content/es", // fr, br, etc.
}
```
then we can use it to copy files as LionDocs does with sublime text extension.

**Additional context**

**Comment by Jalkhov** [comment]
Yes, I like the idea, however, I think it is a good idea to have some other configurations, for several reasons I think, it expands the possibilities and is a bit more organized, I take as an example [liondocs-sublime](https://github.com/liondocs/liondocs-sublime#configuration):

```jsonc
{
  // Absolute paths to the repositories
  "paths":{
    "content": "",
    "translated-content": ""
  },
  // It must be the same as the one in translated-content
  "lang_code":"",
  // Show alerts in successfully silent operations
  "alerts":true
}
```

It doesn't necessarily have to be `from` -> `to` because I think in the long run it will require bidirectional operations. Also, having the path to the repositories and the language to be used in different variables helps a lot at the code level, at least that's what happened with the sublime plugin. Sometimes it was necessary to use only the language code and if we take it to this case, it would be necessary to cut the path to separate it from the code, easy, yes, but it can be avoided.

**Comment by JuanVqz** [comment]
I didn't want to tie to `content` and `translated-content` but yeah maybe I should use them. and yep, more options can be added in the future, how do you use `lang_code`?

**Comment by JuanVqz** [comment]
small pick stuff, I'll use `translated_content` because `lang_code` uses `_`, to be consistent and because I'm used to `_` instead of `-`. :+1:
